import os
import argparse


"""
Simple script used to remove all the keypoint annotation by 
either director or open3d. Note that the removed annotation
is usually generated by keypoint_mesh2img_...py
"""
parser = argparse.ArgumentParser()
parser.add_argument('--img_keypoint_relative_path', type=str, default='mug_2_keypoint_image.yaml',
                    help='The path to save the image keypoint yaml file. '
                         'Relative to the log_root/2018-11-23-../processed')
parser.add_argument('--log_root_path', type=str, default='/home/wei/data/pdc/logs_proto',
                    help='Full path/to/logs_proto')
parser.add_argument('--real_run', type=bool, default=True)
args = parser.parse_args()


def main(real_run: bool = False):
    log_root_path: str = args.log_root_path
    assert os.path.exists(log_root_path) and os.path.isdir(log_root_path)
    for scene_name in os.listdir(log_root_path):
        scene_root_path = os.path.join(log_root_path, scene_name)
        scene_processed_path = os.path.join(scene_root_path, 'processed')
        annotation_path = os.path.join(scene_processed_path, args.img_keypoint_relative_path)
        if os.path.exists(annotation_path):
            print('Removing %s' % annotation_path)
            if real_run:
                os.remove(annotation_path)


if __name__ == '__main__':
    main(args.real_run)
